diff a/drivers/video/fbdev/msm/Makefile b/drivers/video/fbdev/msm/Makefile	(rejected hunks)
@@ -2,6 +2,8 @@ ccflags-y += -I$(src) -Idrivers/staging/android
 
 obj-$(CONFIG_FB_MSM_MDSS_MHL3) += mhl3/
 obj-$(CONFIG_MSM_DBA) += msm_dba/
+# SW4-HL-Display-GlanceMode-00+_20170524
+obj-$(CONFIG_AOD_FEATURE) +=fih/
 
 mdss-mdp3-objs = mdp3.o mdp3_dma.o mdp3_ctrl.o dsi_status_v2.o
 mdss-mdp3-objs += mdp3_ppp.o mdp3_ppp_hwio.o mdp3_ppp_data.o
@@ -37,6 +39,10 @@ mdss-dsi-objs += msm_mdss_io_8974.o
 mdss-dsi-objs += mdss_dsi_phy.o
 mdss-dsi-objs += mdss_dsi_phy_v3.o
 mdss-dsi-objs += mdss_dsi_clk.o
+ifeq ($(CONFIG_PXLW_IRIS3),y)
+mdss-dsi-objs += mdss_dsi_iris3_ioctl.o mdss_dsi_iris3_lightup_ocp.o mdss_dsi_iris3_lightup.o mdss_dsi_iris3_lut.o
+mdss-dsi-objs += mdss_dsi_iris3_pq.o mdss_dsi_iris3_lp.o
+endif
 obj-$(CONFIG_FB_MSM_MDSS) += mdss-dsi.o
 obj-$(CONFIG_FB_MSM_MDSS) += mdss_panel.o
 obj-$(CONFIG_FB_MSM_MDSS) += mdss_hdmi_util.o
