diff a/drivers/input/misc/Makefile b/drivers/input/misc/Makefile	(rejected hunks)
@@ -81,3 +81,4 @@ obj-$(CONFIG_INPUT_YEALINK)		+= yealink.o
 obj-$(CONFIG_INPUT_IDEAPAD_SLIDEBAR)	+= ideapad_slidebar.o
 obj-$(CONFIG_INPUT_PIXART_OTS_PAT9125_SWITCH)	+= ots_pat9125/
 obj-$(CONFIG_INPUT_STMVL53L0)                 += vl53L0/
+obj-$(CONFIG_INPUT_AH1902)      += ah1902.o
